[project]
name = "x2mqtt"
description = "A generic platform to poll data from an API and publish it to MQTT. Uses Home Assistant discovery."
version = "0.3.4"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["paho-mqtt>=2.1.0", "python-slugify~=8.0"]
classifiers = ["Private :: Do not Upload"]
license = "GPL-3.0"
license-files = ["LICENSE"]
